"""add_4326

Revision ID: 217be544351c
Revises: 00b46ee3821c
Create Date: 2025-12-29 17:11:31.360078

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "217be544351c"
down_revision: Union[str, Sequence[str], None] = "00b46ee3821c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "features",
        "geom",
        existing_type=geoalchemy2.types.Geometry(
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geometry(
            srid=4326,
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "features",
        "geom",
        existing_type=geoalchemy2.types.Geometry(
            srid=4326,
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        type_=geoalchemy2.types.Geometry(
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
