"""create point_features

Revision ID: 9c14f4771b41
Revises:
Create Date: 2025-12-30 15:14:01.831355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "9c14f4771b41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_points",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feature_points_geom_gist",
        "feature_points",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_feature_points_geom_gist",
        table_name="feature_points",
        postgresql_using="gist",
    )
    op.drop_index(
        "idx_feature_points_geom", table_name="feature_points", postgresql_using="gist"
    )
    op.drop_table("feature_points")
    # ### end Alembic commands ###
