"""init_asyncpg

Revision ID: f35cd4ee7ac9
Revises: 21975ee23721
Create Date: 2025-12-29 14:34:25.068462

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f35cd4ee7ac9"
down_revision: Union[str, Sequence[str], None] = "21975ee23721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
