"""add_layers

Revision ID: 7f4dbcd151ee
Revises: 0d9dcd16a92c
Create Date: 2026-01-06 23:50:48.351202

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = "7f4dbcd151ee"
down_revision: Union[str, Sequence[str], None] = "0d9dcd16a92c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "layers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False, unique=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("geometry_type", sa.Text(), nullable=False),
        sa.Column("srid", sa.Integer(), server_default=sa.text("4326"), nullable=False),
        sa.Column("storage_table", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    bind = op.get_bind()

    layers = sa.Table(
        "layers",
        sa.MetaData(),
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("geometry_type", sa.Text(), nullable=False),
        sa.Column("storage_table", sa.Text(), nullable=False),
        sa.Column("srid", sa.Integer(), nullable=False),
    )

    _controller_data = [
        {
            "id": uuid.UUID("11111111-1111-1111-1111-111111111111"),
            "name": "points",
            "title": "Points",
            "geometry_type": "Point",
            "storage_table": "feature_points",
            "srid": 4326,
        },
        {
            "id": uuid.UUID("22222222-2222-2222-2222-222222222222"),
            "name": "polygons",
            "title": "Polygons",
            "geometry_type": "Polygon",
            "storage_table": "feature_polygons",
            "srid": 4326,
        },
        {
            "id": uuid.UUID("33333333-3333-3333-3333-333333333333"),
            "name": "lines",
            "title": "Lines",
            "geometry_type": "LineString",
            "storage_table": "feature_lines",
            "srid": 4326,
        },
        {
            "id": uuid.UUID("44444444-4444-4444-4444-444444444444"),
            "name": "multipoints",
            "title": "MultiPoints",
            "geometry_type": "MultiPoint",
            "storage_table": "feature_multipoints",
            "srid": 4326,
        },
        {
            "id": uuid.UUID("55555555-5555-5555-5555-555555555555"),
            "name": "multipolygons",
            "title": "MultiPolygons",
            "geometry_type": "MultiPolygon",
            "storage_table": "feature_multipolygons",
            "srid": 4326,
        },
        {
            "id": uuid.UUID("66666666-6666-6666-6666-666666666666"),
            "name": "multilines",
            "title": "MultiLines",
            "geometry_type": "MultiLineString",
            "storage_table": "feature_multilines",
            "srid": 4326,
        },
    ]

    insert_stmt = postgresql.insert(layers).values(_controller_data)
    update_cols = {
        "name": insert_stmt.excluded.name,
        "title": insert_stmt.excluded.title,
        "geometry_type": insert_stmt.excluded.geometry_type,
        "storage_table": insert_stmt.excluded.storage_table,
        "srid": insert_stmt.excluded.srid,
    }

    upsert_stmt = insert_stmt.on_conflict_do_update(
        index_elements=[layers.c.id],
        set_=update_cols,
    )

    bind.execute(upsert_stmt)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("layers")
    # ### end Alembic commands ###
